### ISSUE TITLE
Using all time points for classification

### ISSUE THREAD

**Issue by Mensen** [scrouzet/classifyEEG#1]
In the example analysis the classification is performed for each time point separately in a loop.

I'd like to run the classifier over all channels and time points in my EEG as a first pass and only if that works breakdown the effect into channels. The reason for this is that I suspect some of the classification power lies in the temporal pattern of the effect and if run for each time point I will lose this pattern.

I've tried some simple adjustments to the scripts but since the data is now a 3D array, many of the functions fail.

Could you advise on how to perform the classification with both channels and time points as predictors?

**Comment by scrouzet** [comment]
Hi, sorry for the delayed answer, I did not receive a notification from github.

Hope it can still be useful. You should definitely not input a 3D array to the functions. You need to reshape your data so that it fits a regular machine learning 2D table, with one line per observation and one column per variable. In your case, that means that you will have a lot of column : let say you have 64 electrodes and 500 timepoints, you will end up with 64*500 = 32000 columns. It is a lot when you compare it to the number of trial (observation) but it can work. We did this exact analysis in a paper published recently :
http://www.sciencedirect.com/science/article/pii/S1053811915009131
We used SVM in this study which may work better in this type of situation than Logistic Regression (which is what I used in general for time-resolved analysis).

**Comment by Mensen** [comment]
Thanks for the response... better late than never.

Your suggested approach of 3rd dimension concatenation is precisely what I ended up doing and the results seem fine. I can't help but feel that some element may nonetheless be missing as treating them as independent features disregards the spatio-temporal structure that might influence the results. The math probably works out to the same anyways.

I did have a problem when testing the SVM approach. I'll post a new issue on that once I get back to that data analysis.

**Comment by scrouzet** [comment]
I definitely agree that treating time-points as independent features is suboptimal (one thing among other is the strong autocorrelation in EEG, so that neighboring points will tend to give similar info). But if one wants to take advantage of the spatio-temporal structure, one needs a good model of it. I personally don't, but would be extremely interested if someone studied this aspect.

I don't use the SVM code often and definitely don't validate all the code every time I make a change, so please post your issue with it.
